# general settings
name: AverNet_DAVIS
model_type: VideoRecurrentModel
scale: 1
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DAVISTrainingDataset
    type: TUDVideoDataset
    scale: 1
    dataroot_lq: datasets/DAVIS_LQ # The dataroot of LQ frames
    dataroot_gt: datasets/DAVIS # The dataroot of GT frames
    meta_info_file: basicsr/data/meta_info/DAVIS_meta_info.txt # The path of video meta information
    io_backend:
      type: disk

    filename_ext: jpg
    filename_tmpl: 05d
    num_frame: 12
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    test_mode: false

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DAVISSubset
    type: VideoRecurrentTestDataset
    dataroot_gt: datasets/DAVISSubset/gt
    dataroot_lq: datasets/DAVISSubset/lq

    cache_data: true
    io_backend:
      type: disk

    num_frame: -1

# network structures
network_g:
  type: AverNet
  mid_channels: 96
  prompt_dim: 96
  prompt_size: 96
  num_blocks: 7
  keyframe_interval: 6
  spynet_pretrained: experiments/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.25

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: psnr
    ssim:
      type: ssim

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True